/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_12 (
    input clk,
    input rst,
    input [48:0] blue,
    input [48:0] green,
    output reg [6:0] rows,
    output reg [6:0] out_blue,
    output reg [6:0] out_green
  );
  
  
  
  wire [3-1:0] M_mycounter_value;
  counter_19 mycounter (
    .clk(clk),
    .rst(rst),
    .value(M_mycounter_value)
  );
  
  integer j;
  
  always @* begin
    rows = 7'h00;
    out_blue = 7'h7f;
    out_green = 7'h7f;
    rows[(M_mycounter_value)*1+0-:1] = 1'h1;
    out_blue = ~blue[(M_mycounter_value)*7+6-:7];
    out_green = ~green[(M_mycounter_value)*7+6-:7];
  end
endmodule
