/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module position_13 (
    input clk,
    input rst,
    input [4:0] move,
    output reg [48:0] green,
    output reg [2:0] row,
    output reg [2:0] column
  );
  
  
  
  reg [6:0] M_pos_d, M_pos_q = 1'h0;
  
  always @* begin
    M_pos_d = M_pos_q;
    
    green[0+6-:7] = 7'h41;
    green[7+6-:7] = 7'h00;
    green[14+6-:7] = 7'h00;
    green[21+6-:7] = 7'h00;
    green[28+6-:7] = 7'h00;
    green[35+6-:7] = 7'h00;
    green[42+6-:7] = 7'h41;
    row = 1'h0;
    column = 1'h0;
    if (M_pos_q == 1'h0) begin
      M_pos_d = M_pos_q + 1'h1;
    end
    if (move == 1'h1) begin
      if (M_pos_q - 3'h7 < 1'h1) begin
        
      end else begin
        M_pos_d = M_pos_q - 3'h7;
      end
    end
    if (move == 2'h2) begin
      if (M_pos_q + 3'h7 > 6'h31) begin
        
      end else begin
        M_pos_d = M_pos_q + 3'h7;
      end
    end
    if (move == 2'h3) begin
      if (M_pos_q + 1'h1 > 6'h31) begin
        
      end else begin
        M_pos_d = M_pos_q + 1'h1;
      end
    end
    if (move == 3'h4) begin
      if (M_pos_q - 1'h1 < 1'h1) begin
        
      end else begin
        M_pos_d = M_pos_q - 1'h1;
      end
    end
    if (M_pos_q < 1'h1) begin
      M_pos_d = 1'h1;
    end
    if (M_pos_q == 1'h1) begin
      green[0+6-:7] = 7'h40;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 1'h1;
    end
    if (M_pos_q == 2'h2) begin
      green[0+6-:7] = 7'h20;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 2'h2;
    end
    if (M_pos_q == 2'h3) begin
      green[0+6-:7] = 7'h10;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 2'h3;
    end
    if (M_pos_q == 3'h4) begin
      green[0+6-:7] = 7'h08;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 3'h4;
    end
    if (M_pos_q == 3'h5) begin
      green[0+6-:7] = 7'h04;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 3'h5;
    end
    if (M_pos_q == 3'h6) begin
      green[0+6-:7] = 7'h02;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 3'h6;
    end
    if (M_pos_q == 3'h7) begin
      green[0+6-:7] = 7'h01;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 1'h1;
      column = 3'h7;
    end
    if (M_pos_q == 4'h8) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h40;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 1'h1;
    end
    if (M_pos_q == 4'h9) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h20;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 2'h2;
    end
    if (M_pos_q == 4'ha) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h10;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 2'h3;
    end
    if (M_pos_q == 4'hb) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h08;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 3'h4;
    end
    if (M_pos_q == 4'hc) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h04;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 3'h5;
    end
    if (M_pos_q == 4'hd) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h02;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 3'h6;
    end
    if (M_pos_q == 4'he) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h01;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h2;
      column = 3'h7;
    end
    if (M_pos_q == 4'hf) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h40;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 1'h1;
    end
    if (M_pos_q == 5'h10) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h20;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 2'h2;
    end
    if (M_pos_q == 5'h11) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h10;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 2'h3;
    end
    if (M_pos_q == 5'h12) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h08;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 3'h4;
    end
    if (M_pos_q == 5'h13) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h04;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 3'h5;
    end
    if (M_pos_q == 5'h14) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h02;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 3'h6;
    end
    if (M_pos_q == 5'h15) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h01;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 2'h3;
      column = 3'h7;
    end
    if (M_pos_q == 5'h16) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h40;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 1'h1;
    end
    if (M_pos_q == 5'h17) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h20;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 2'h2;
    end
    if (M_pos_q == 5'h18) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h10;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 2'h3;
    end
    if (M_pos_q == 5'h19) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h08;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 3'h4;
    end
    if (M_pos_q == 5'h1a) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h04;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 3'h5;
    end
    if (M_pos_q == 5'h1b) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h02;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 3'h6;
    end
    if (M_pos_q == 5'h1c) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h01;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h4;
      column = 3'h7;
    end
    if (M_pos_q == 5'h1d) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h40;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 1'h1;
    end
    if (M_pos_q == 5'h1e) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h20;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 2'h2;
    end
    if (M_pos_q == 5'h1f) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h10;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 2'h3;
    end
    if (M_pos_q == 6'h20) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h08;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 3'h4;
    end
    if (M_pos_q == 6'h21) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h04;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 3'h5;
    end
    if (M_pos_q == 6'h22) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h02;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 3'h6;
    end
    if (M_pos_q == 6'h23) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h01;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h00;
      row = 3'h5;
      column = 3'h7;
    end
    if (M_pos_q == 6'h24) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h40;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 1'h1;
    end
    if (M_pos_q == 6'h25) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h20;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 2'h2;
    end
    if (M_pos_q == 6'h26) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h10;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 2'h3;
    end
    if (M_pos_q == 6'h27) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h08;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 3'h4;
    end
    if (M_pos_q == 6'h28) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h04;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 3'h5;
    end
    if (M_pos_q == 6'h29) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h02;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 3'h6;
    end
    if (M_pos_q == 6'h2a) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h01;
      green[42+6-:7] = 7'h00;
      row = 3'h6;
      column = 3'h7;
    end
    if (M_pos_q == 6'h2b) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h40;
      row = 3'h7;
      column = 1'h1;
    end
    if (M_pos_q == 6'h2c) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h20;
      row = 3'h7;
      column = 2'h2;
    end
    if (M_pos_q == 6'h2d) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h10;
      row = 3'h7;
      column = 2'h3;
    end
    if (M_pos_q == 6'h2e) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h08;
      row = 3'h7;
      column = 3'h4;
    end
    if (M_pos_q == 6'h2f) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h04;
      row = 3'h7;
      column = 3'h5;
    end
    if (M_pos_q == 6'h30) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h02;
      row = 3'h7;
      column = 3'h6;
    end
    if (M_pos_q == 6'h31) begin
      green[0+6-:7] = 7'h00;
      green[7+6-:7] = 7'h00;
      green[14+6-:7] = 7'h00;
      green[21+6-:7] = 7'h00;
      green[28+6-:7] = 7'h00;
      green[35+6-:7] = 7'h00;
      green[42+6-:7] = 7'h01;
      row = 3'h7;
      column = 3'h7;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pos_q <= 1'h0;
    end else begin
      M_pos_q <= M_pos_d;
    end
  end
  
endmodule
