/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module position_11 (
    input clk,
    input rst,
    input [4:0] move,
    output reg [5:0] out
  );
  
  
  
  reg [5:0] M_pos_d, M_pos_q = 1'h0;
  
  always @* begin
    M_pos_d = M_pos_q;
    
    if (M_pos_q == 1'h0) begin
      M_pos_d = M_pos_q + 1'h1;
    end
    if (move == 3'h4) begin
      if (M_pos_q + 1'h1 > 6'h31) begin
        
      end else begin
        M_pos_d = M_pos_q + 1'h1;
      end
    end
    if (move == 1'h0) begin
      if (M_pos_q - 3'h7 < 1'h1) begin
        
      end else begin
        M_pos_d = M_pos_q - 3'h7;
      end
    end
    if (move == 2'h2) begin
      if (M_pos_q + 3'h7 > 6'h31) begin
        
      end else begin
        M_pos_d = M_pos_q + 3'h7;
      end
    end
    if (move == 2'h3) begin
      if (M_pos_q - 1'h1 < 1'h1) begin
        
      end else begin
        M_pos_d = M_pos_q - 1'h1;
      end
    end
    out = M_pos_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pos_q <= 1'h0;
    end else begin
      M_pos_q <= M_pos_d;
    end
  end
  
endmodule
