/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_Seg_16 (
    input clk,
    input rst,
    input [5:0] move_counter,
    output reg [6:0] out_ones,
    output reg [6:0] out_tens
  );
  
  
  
  always @* begin
    out_ones = 7'h00;
    out_tens = 7'h00;
    if (move_counter == 1'h0 || move_counter == 4'ha || move_counter == 5'h14 || move_counter == 5'h1e) begin
      out_ones = 7'h7e;
    end else begin
      if (move_counter == 1'h1 || move_counter == 4'hb || move_counter == 5'h15 || move_counter == 5'h1f) begin
        out_ones = 7'h30;
      end else begin
        if (move_counter == 2'h2 || move_counter == 4'hc || move_counter == 5'h16 || move_counter == 6'h20) begin
          out_ones = 7'h6d;
        end else begin
          if (move_counter == 2'h3 || move_counter == 4'hd || move_counter == 5'h17 || move_counter == 6'h21) begin
            out_ones = 7'h79;
          end else begin
            if (move_counter == 3'h4 || move_counter == 4'he || move_counter == 5'h18) begin
              out_ones = 7'h33;
            end else begin
              if (move_counter == 3'h5 || move_counter == 4'hf || move_counter == 5'h19) begin
                out_ones = 7'h5b;
              end else begin
                if (move_counter == 3'h6 || move_counter == 5'h10 || move_counter == 5'h1a) begin
                  out_ones = 7'h5f;
                end else begin
                  if (move_counter == 3'h7 || move_counter == 5'h11 || move_counter == 5'h1b) begin
                    out_ones = 7'h70;
                  end else begin
                    if (move_counter == 4'h8 || move_counter == 5'h12 || move_counter == 5'h1c) begin
                      out_ones = 7'h7f;
                    end else begin
                      if (move_counter == 4'h9 || move_counter == 5'h13 || move_counter == 5'h1d) begin
                        out_ones = 7'h7b;
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    if (move_counter < 4'ha) begin
      out_tens = 7'h7e;
    end else begin
      if (move_counter < 5'h14) begin
        out_tens = 7'h30;
      end else begin
        if (move_counter < 5'h1e) begin
          out_tens = 7'h6d;
        end else begin
          if (move_counter < 6'h28) begin
            out_tens = 7'h79;
          end
        end
      end
    end
  end
endmodule
